services:
  db:
    # Uses the standard Debian-based image for Postgres 14
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: data_pipeline
      # Required: Directs Postgres to use the custom internal path
      PGDATA: /var/lib/postgresql/db/pgdata
    ports:
      - "5432:5432"
    volumes:
      # Maps the volume to specified path
      - postgres_data:/var/lib/postgresql/db
      # run the script on startup
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: